site_name: F*ckingNode
site_description: The f*cking chaos of maintaining NodeJS projects ends here.
site_url: https://zakahacecosas.github.io/FuckingNode
site_author: ZakaHaceCosas
copyright: ZakaHaceCosas

repo_name: ZakaHaceCosas/FuckingNode
repo_url: https://github.com/ZakaHaceCosas/FuckingNode

docs_dir: "website"

nav:
  - Home: "index.md"

  - Manual:
      - Installation: "manual/index.md"

theme:
  name: material

  # logo: /path/to/logo.png
  # favicon: /path/to/logo.png (when we have it)

  features:
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - navigation.expand

    - content.code.copy

  palette:
    - scheme: default
      primary: green
      accent: green

plugins:
  - social
  - redirects:
      redirect_maps:
        "repo.md": "https://github.com/ZakaHaceCosas/FuckingNode"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.blocks.caption