name: Nix hash

on: workflow_dispatch

permissions:
  contents: read
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Nix
              uses: cachix/install-nix-action@v31
              with:
                  nix_path: nixpkgs=channel:nixos-unstable
                  extra_nix_config: |
                      experimental-features = nix-command flakes

            - name: Get hashes for Nix
              run: |
                  nix run .#hashes
